### PR TITLE
Change default port from `5000` to `3000`

### PR DESCRIPTION
**Pull request by kud**
Due to a conflict with AirPlay, it could be interesting to change the default port: https://developer.apple.com/forums/thread/682332

related: https://github.com/vercel/serve/issues/672
info: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

### CODE REVIEW

**Comment by kachkaev** [comment]
3000 is used by Next.js and CRA by default, which means that ports will often clash in practice. Having said that, I don’t know what port to suggest.

Nice-looking numbers like `6000`, `9000` or `10000` are all used for something else, [according to Wikipedia](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers). Maybe 3030? 🤷

**Comment by leo** [comment]
I don't think it will be common that people will run tools like Next.js and CRA and the same time as `serve`, but if they do, `--listen <port>` can be used for defining a custom one.

`3000` as the new default sounds good to me!

**Comment by leo** [comment]
Thank you!

**Comment by kud** [comment]
My pleasure 😊

**Comment by mariojfduarte** [comment]
If you have a Docker Swarm mode cluster set up with traefik as a load balance to do wtv, don't forget to change alll your docker files that use _serve_ default port in order to prevent **Bad Gateway** connection errors.

`
...
RUN yarn global add serve 
...
CMD serve -s **-p 5000** build
...

`

**Pull request merged**
