### PR TITLE
patch: Patch path-to-regexp security vulnerability

### PR DESCRIPTION
**Pull request by alana-cruickshank**
closes vercel/serve#811
see GHSA-9wv6-86v2-598j

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@alana-cruickshank 

- Your PR overlaps with https://github.com/vercel/serve/pull/812. Is there some reason you wanted to override the other PR?

**Comment by alana-cruickshank** [comment]
@MikeMcC399 - Sorry!  I didn't see a PR linked to that issue.  Feel free to close!

**Comment by MikeMcC399** [comment]
@alana-cruickshank 

> Sorry! I didn't see a PR linked to that issue, and #812 wasn't opened when I picked this up. Feel free to close!

- Thanks for confirming! I can't close this PR, since I'm not a maintainer of this repo. I'm just the author of the issue 
#811 that you linked to. You should be able to close your PR yourself though ⬇️

**Comment by AndyBitz** [comment]
Thanks for the PR @alana-cruickshank!

I've just merged https://github.com/vercel/serve/pull/812 which includes the new version of `serve-handler`.
I'll publish it shortly.

**Pull request closed without merging**
